"use client";
import{Suspense,useCallback,useEffect,useMemo,useRef,useState}from"react";import{usePathname,useRouter,useSearchParams}from"next/navigation";import{Search}from"lucide-react";import{TicketRow}from"@/components/TicketRow";import{useAppDispatch,useAppSelector}from"@/store/hooks";import{setFilters}from"@/store/store";import{CATEGORIES,PRIORITIES,STATUSES,type Ticket,type TicketFilters,type TicketPage}from"@/lib/types";import{nextStatus}from"@/lib/validation";import{notifyCounts}from"@/components/Header";
const empty:TicketFilters={status:"",priority:"",category:"",triage_decision:"",search:""};
export default function TicketsPage(){return <Suspense fallback={<State text="Loading tickets…"/>}><TicketsContent/></Suspense>}
function TicketsContent(){const searchParams=useSearchParams(),router=useRouter(),path=usePathname(),dispatch=useAppDispatch(),agent=useAppSelector(s=>s.agent.current);const filters=useMemo(()=>({...empty,...Object.fromEntries(Object.keys(empty).map(k=>[k,searchParams.get(k)??""]))}),[searchParams]);const[search,setSearch]=useState(filters.search),[data,setData]=useState<TicketPage|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[pending,setPending]=useState<Ticket[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[bulkBusy,setBulkBusy]=useState(false),[bulkResults,setBulkResults]=useState<string[]>([]);const since=useRef(new Date().toISOString());
 useEffect(()=>{setSearch(filters.search);dispatch(setFilters(filters))},[filters,dispatch]);
 const update=useCallback((key:string,value:string)=>{const q=new URLSearchParams(searchParams);if(value)q.set(key,value);else q.delete(key);if(key!=="page")q.delete("page");router.replace(`${path}?${q}`)},[searchParams,router,path]);
 useEffect(()=>{const id=setTimeout(()=>{if(search!==filters.search)update("search",search)},300);return()=>clearTimeout(id)},[search,filters.search,update]);
 const load=useCallback(async(reset=true,cursor?:string|null)=>{if(reset)setLoading(true);setError("");try{const q=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));q.set("pageSize","25");if(cursor)q.set("cursor",cursor);const r=await fetch(`/api/tickets?${q}`);if(!r.ok)throw new Error("Could not load tickets");const next=await r.json() as TicketPage;setData(previous=>{if(reset||!previous)return next;const ids=new Set(previous.items.map(t=>t.id));return{...next,items:[...previous.items,...next.items.filter(t=>!ids.has(t.id))]}})}catch(e){setError(e instanceof Error?e.message:"Could not load tickets")}finally{setLoading(false)}},[filters]);useEffect(()=>{setSelected(new Set());load(true)},[load]);
 useEffect(()=>{const poll=async()=>{try{const r=await fetch(`/api/tickets/updates?since=${encodeURIComponent(since.current)}`);if(!r.ok)return;const json=await r.json();since.current=new Date().toISOString();const visible=new Set(data?.items.map(t=>t.id));setPending(current=>{const merged=new Map(current.map(t=>[t.id,t]));for(const ticket of json.items as Ticket[])if(!visible.has(ticket.id))merged.set(ticket.id,ticket);return[...merged.values()]})}catch{}};const id=setInterval(poll,5000);return()=>clearInterval(id)},[data]);
 const showUpdates=()=>{setPending([]);setSelected(new Set());load(true)};
 const selectTicket=useCallback((id:string,checked:boolean)=>setSelected(current=>{const next=new Set(current);if(checked)next.add(id);else next.delete(id);return next}),[]);
 const runBulk=async(kind:"claim"|"status")=>{if(!data||!selected.size||bulkBusy)return;setBulkBusy(true);setBulkResults([]);const chosen=data.items.filter(t=>selected.has(t.id)),before=new Map(chosen.map(t=>[t.id,t]));setData(current=>current?{...current,items:current.items.map(t=>!selected.has(t.id)?t:kind==="claim"?{...t,assigned_to:agent}:{...t,status:nextStatus(t.status)??t.status})}:current);const settled=await Promise.allSettled(chosen.map(async ticket=>{const status=nextStatus(ticket.status);if(kind==="status"&&!status)throw new Error("No valid next status");const r=await fetch(`/api/tickets/${ticket.id}/${kind==="claim"?"claim":"status"}`,{method:kind==="claim"?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(kind==="claim"?{agentId:agent}:{status})});const body=await r.json();if(!r.ok)throw new Error(body.error||"Request failed");return body as Ticket}));setData(current=>{if(!current)return current;const resultById=new Map<string,Ticket>(),failed=new Set<string>();settled.forEach((result,index)=>{const id=chosen[index].id;if(result.status==="fulfilled")resultById.set(id,result.value);else failed.add(id)});return{...current,items:current.items.map(t=>resultById.get(t.id)??(failed.has(t.id)?before.get(t.id)??t:t))}});setBulkResults(settled.map((result,index)=>`${chosen[index].external_id}: ${result.status==="fulfilled"?"succeeded":result.reason instanceof Error?result.reason.message:"failed"}`));setSelected(new Set());setBulkBusy(false);notifyCounts()};
 return <div className="container" style={{paddingTop:34,paddingBottom:50}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16}}><div><p style={{color:"var(--brand)",fontWeight:800,margin:0}}>OPERATIONS</p><h1 style={{fontSize:34,margin:"6px 0"}}>Tickets</h1><p style={{color:"var(--muted)"}}>Find, triage, and resolve customer issues.</p></div><span className="badge">{data?.total??0} results</span></div>
 {pending.length>0&&<button className="btn" onClick={showUpdates} style={{marginBottom:16}}>{pending.length} updated {pending.length===1?"ticket":"tickets"} — Show</button>}
 <section className="card" style={{padding:16,marginBottom:18}}><div style={{display:"grid",gridTemplateColumns:"minmax(220px,2fr) repeat(4,minmax(130px,1fr))",gap:10,overflowX:"auto"}}><label className="label">Search<div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:10,top:12}}/><input className="field" style={{width:"100%",paddingLeft:34}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subject or body"/></div></label><Filter label="Status" value={filters.status} values={STATUSES} onChange={v=>update("status",v)}/><Filter label="Priority" value={filters.priority} values={PRIORITIES} onChange={v=>update("priority",v)}/><Filter label="Category" value={filters.category} values={CATEGORIES} onChange={v=>update("category",v)}/><Filter label="AI decision" value={filters.triage_decision} values={["auto_accept","manual_review"]} onChange={v=>update("triage_decision",v)}/></div></section>
 {selected.size>0&&<section className="card" style={{padding:14,marginBottom:14,display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><strong>{selected.size} selected</strong><button className="btn" disabled={bulkBusy} onClick={()=>runBulk("claim")}>Claim selected</button><button className="btn secondary" disabled={bulkBusy} onClick={()=>runBulk("status")}>Advance status</button><button className="btn secondary" disabled={bulkBusy} onClick={()=>setSelected(new Set())}>Clear</button></section>}
 {bulkResults.length>0&&<section className="card" aria-live="polite" style={{padding:14,marginBottom:14}}><strong>Bulk results</strong><ul>{bulkResults.map(result=><li key={result}>{result}</li>)}</ul></section>}
 <section className="card" style={{overflowX:"auto"}}>{loading?<State text="Loading tickets…"/>:error?<State text={error} action={<button className="btn" onClick={()=>load(true)}>Retry</button>}/>:!data?.items.length?<State text="No tickets match these filters."/>:<table style={{borderCollapse:"collapse",width:"100%",minWidth:1060,textAlign:"left"}}><thead><tr><th style={{padding:12}}><input aria-label="Select all loaded tickets" type="checkbox" checked={data.items.length>0&&data.items.every(t=>selected.has(t.id))} onChange={e=>setSelected(e.target.checked?new Set(data.items.map(t=>t.id)):new Set())}/></th>{["Subject","Plan","Category","Priority","Status","Agent","Created","Deadline"].map(h=><th key={h} style={{padding:"12px",fontSize:12,color:"var(--muted)"}}>{h}</th>)}</tr></thead><tbody>{data.items.map(t=><TicketRow key={t.id} ticket={t} selected={selected.has(t.id)} onSelect={selectTicket}/>)}</tbody></table>}</section>
 {data?.nextCursor&&<div style={{display:"flex",justifyContent:"center",marginTop:18}}><button className="btn secondary" disabled={loading} onClick={()=>load(false,data.nextCursor)}>Load more tickets</button></div>}</div>}
function Filter({label,value,values,onChange}:{label:string;value:string;values:readonly string[];onChange:(v:string)=>void}){return <label className="label">{label}<select className="field" value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{values.map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label>}
function State({text,action}:{text:string;action?:React.ReactNode}){return <div style={{padding:60,textAlign:"center"}}><p>{text}</p>{action}</div>}
