"use client";
import{useCallback,useEffect,useRef,useState}from"react";import{useParams}from"next/navigation";import Link from"next/link";import{AGENTS,type Ticket}from"@/lib/types";import{useAppSelector}from"@/store/hooks";import{Deadline}from"@/components/Deadline";import{formatDate}from"@/components/TicketRow";import{nextStatus}from"@/lib/validation";import{safeAttachmentUrl}from"@/lib/security";import{notifyCounts}from"@/components/Header";
const actions={in_progress:"Start Progress",resolved:"Resolve",open:"Reopen"} as const;
export default function Detail(){const{id}=useParams<{id:string}>(),agent=useAppSelector(s=>s.agent.current),[ticket,setTicket]=useState<Ticket|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");const claimLock=useRef(false),statusLock=useRef(false),retriageLock=useRef(false);
 const load=useCallback(async()=>{setError("");try{const r=await fetch(`/api/tickets/${id}`);if(r.status===404){setError("NOT_FOUND");return}if(!r.ok)throw new Error();setTicket(await r.json())}catch{setError("Could not load this ticket.")}},[id]);useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
 const claim=async()=>{if(!ticket||claimLock.current)return;claimLock.current=true;setBusy("claim");setNotice("");const previous=ticket.assigned_to;setTicket({...ticket,assigned_to:agent});try{const r=await fetch(`/api/tickets/${id}/claim`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:agent})});if(!r.ok){const b=await r.json();throw Object.assign(new Error(b.error),{status:r.status})}setTicket(await r.json());notifyCounts()}catch(e){setTicket(t=>t?{...t,assigned_to:previous}:t);setNotice((e as {status?:number}).status===409?"This ticket was claimed by another agent.":"Claim failed. Please try again.");notifyCounts()}finally{claimLock.current=false;setBusy("")}};
 const changeStatus=async()=>{if(!ticket||statusLock.current)return;const status=nextStatus(ticket.status);if(!status)return;statusLock.current=true;setBusy("status");setNotice("");try{const r=await fetch(`/api/tickets/${id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw new Error();setTicket(await r.json());notifyCounts()}catch{setNotice("Status update failed.")}finally{statusLock.current=false;setBusy("")}};
 const retriage=async()=>{if(retriageLock.current)return;retriageLock.current=true;setBusy("retriage");setNotice("");try{const r=await fetch(`/api/tickets/${id}/retriage`,{method:"POST"});const body=await r.json();if(!r.ok)throw new Error(body.error);setTicket(body);setNotice("AI triage refreshed and sent for review.");notifyCounts()}catch(e){setNotice(e instanceof Error?e.message:"Re-triage failed.")}finally{retriageLock.current=false;setBusy("")}};
 if(error==="NOT_FOUND")return <div className="container" style={{paddingTop:60}}><h1>Ticket not found</h1><Link href="/tickets">Back to tickets</Link></div>;if(error)return <Screen text={error} action={<button className="btn" onClick={load}>Retry</button>}/>;if(!ticket)return <Screen text="Loading ticket…"/>;
 const url=safeAttachmentUrl(ticket.attachment_url),agentName=ticket.assigned_to?(AGENTS[ticket.assigned_to as keyof typeof AGENTS]??"Unknown agent"):"Unassigned",next=nextStatus(ticket.status),aiPriority=ticket.ai_priority??ticket.priority;
 return <div className="container" style={{paddingTop:34,paddingBottom:50}}><Link href="/tickets">← All tickets</Link><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:20,margin:"20px 0",flexWrap:"wrap"}}><div style={{minWidth:0}}><span className="badge">{ticket.external_id}</span><h1 style={{fontSize:32,overflowWrap:"anywhere"}}>{ticket.subject||"No subject"}</h1><p style={{color:"var(--muted)"}}>{ticket.customer_id} · {ticket.customer_plan} · Created {formatDate(ticket.created_at)}</p></div><Deadline createdAt={ticket.created_at} priority={ticket.priority}/></div>{notice&&<p className="card" role="alert" style={{padding:14,color:"var(--danger)"}}>{notice}</p>}<div style={{display:"grid",gridTemplateColumns:"minmax(0,2fr) minmax(280px,1fr)",gap:18}}><section className="card" style={{padding:24,minWidth:0}}><h2>Customer message</h2><p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",lineHeight:1.6}}>{ticket.body||"No message provided."}</p><h2 style={{marginTop:32}}>AI triage</h2><p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{ticket.summary||"No summary available."}</p><dl style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:14}}><Info label="Decision" value={ticket.triage_decision}/><Info label="AI category" value={ticket.category}/><Info label="AI suggested priority" value={aiPriority}/><Info label="Final priority" value={ticket.priority}/></dl>{ticket.ai_priority&&ticket.ai_priority!==ticket.priority&&<p><strong>Adjustment reason:</strong> {ticket.review_reason||"Final priority was adjusted during review."}</p>}<h2 style={{marginTop:32}}>Attachment</h2>{url?<a href={url} target="_blank" rel="noopener noreferrer">Open safe attachment ↗</a>:<p style={{color:"var(--muted)"}}>{ticket.attachment_url?"Unsafe or invalid attachment URL blocked.":"No attachment."}</p>}</section><aside className="card" style={{padding:22,height:"fit-content"}}><h2>Actions</h2><Info label="Status" value={ticket.status}/><Info label="Assigned to" value={agentName}/>{!ticket.assigned_to&&<button className="btn" disabled={busy==="claim"} onClick={claim}>{busy==="claim"?"Claiming…":"Claim Ticket"}</button>}{next&&<button className="btn secondary" style={{marginLeft:8}} disabled={busy==="status"} onClick={changeStatus}>{busy==="status"?"Updating…":actions[next]}</button>}<button className="btn secondary" style={{marginTop:10}} disabled={busy==="retriage"} onClick={retriage}>{busy==="retriage"?"Re-running…":"Re-run AI"}</button>{!next&&<p style={{color:"var(--muted)"}}>Legacy status cannot be changed here.</p>}</aside></div></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt style={{color:"var(--muted)",fontSize:12}}>{label}</dt><dd style={{margin:0,fontWeight:700,overflowWrap:"anywhere"}}>{value.replaceAll("_"," ")}</dd></div>}function Screen({text,action}:{text:string;action?:React.ReactNode}){return <div className="container" style={{padding:70,textAlign:"center"}}><p>{text}</p>{action}</div>}
